# Generated by Django 4.0.5 on 2022-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_post_date_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Gadgets', 'Gadgets'), ('Science', 'Science'), ('Social Media', 'Social Media'), ('Car News', 'Car news'), ('WorldWide', 'WorldWide')], default='-------', max_length=200, null=True),
        ),
    ]
