# Generated by Django 4.0.5 on 2022-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Gadgets', 'Gadgets'), ('Science', 'Science'), ('Social Media', 'Social Media'), ('WorldWide', 'WorldWide'), ('new', 'new'), ('technology', 'technology'), ('coding', 'coding')], default='coding', max_length=200, null=True),
        ),
    ]
