# Generated by Django 4.0.5 on 2022-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('technology', 'technology'), ('coding', 'coding'), ('worldwide', 'worldwide'), ('social media', 'social media'), ('science', 'science'), ('gadgets', 'gadgets'), ('fashion', 'fashion')], default='coding', max_length=200, null=True),
        ),
    ]
