# Generated by Django 4.0.5 on 2022-08-02 18:16

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0036_subscribedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Tutorial',
            },
        ),
    ]
