# Generated by Django 4.0.5 on 2022-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0037_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video')], default='article', max_length=10),
        ),
    ]
