# Generated by Django 4.0.5 on 2022-08-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0040_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
