# Generated by Django 4.0.5 on 2022-08-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0041_remove_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='CommentPost',
        ),
    ]
