# Generated by Django 4.0.5 on 2022-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0044_category_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.CharField(blank=True, default='Vivamus non condimentum orci. Pellentesque venenatis nibh sit amet est vehicula lobortis.', max_length=200, null=True),
        ),
    ]
