# Generated by Django 4.0.5 on 2022-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0045_category_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.BooleanField(default=False),
        ),
    ]
